#!/bin/sh
# Generated by opip kit create. Installs the bundled .opip on this machine.
set -eu
KIT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
PY=""
if [ -x "$KIT_DIR/runtime/bin/python3" ]; then
  PY="$KIT_DIR/runtime/bin/python3"
elif [ -x "$KIT_DIR/runtime/bin/python" ]; then
  PY="$KIT_DIR/runtime/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY=$(command -v python3)
elif command -v python >/dev/null 2>&1; then
  PY=$(command -v python)
else
  echo "error: no Python found. Re-create the kit with --with-runtime." >&2
  exit 1
fi

OPIP_PYZ="$KIT_DIR/opip.pyz"
if [ ! -f "$OPIP_PYZ" ]; then
  echo "error: missing $OPIP_PYZ" >&2
  exit 1
fi

BUNDLE=""
for f in "$KIT_DIR"/packages/*.opip; do
  if [ -f "$f" ]; then
    BUNDLE="$f"
    break
  fi
done
if [ -z "$BUNDLE" ]; then
  echo "error: no .opip bundle under packages/" >&2
  exit 1
fi

VENV="${OPIP_KIT_VENV:-$HOME/.local/share/opip/venvs/kit}"
mkdir -p "$(dirname "$VENV")"

echo "Using Python: $PY"
echo "Installing:   $BUNDLE"
echo "Into venv:    $VENV"

if [ -f "$BUNDLE.rsg" ] || [ -f "${BUNDLE}.rsg" ]; then
  "$PY" "$OPIP_PYZ" verify "$BUNDLE" --require-signature || true
fi

"$PY" "$OPIP_PYZ" install "$BUNDLE" --venv "$VENV" -y

if [ -f "$KIT_DIR/pip-rns.pyz" ]; then
  echo "Installing pip-rns/opip tools onto PATH (self-install --user)..."
  "$PY" "$KIT_DIR/pip-rns.pyz" self-install --user -y || true
fi

echo "Done. Activate with: source $VENV/bin/activate"
if [ -x "$KIT_DIR/Run" ]; then
  echo "Or run the AppImage-style launcher: $KIT_DIR/Run"
fi
