# Copyright (c) 2026, Quad4 (quad4.io)
"""Install pip-rns/opip onto PATH without requiring system pip."""

from __future__ import annotations

import os
import shutil
import site
import sys
import zipfile
from pathlib import Path

from opip.install import (
    InstallError,
    _find_pip,
    _uv_available,
    ensure_venv,
    install_wheel_manual,
)

SHIMS = (
    ("opip", "opip.cli", "main"),
    ("pip-rns", "pip_rns.cli", "main"),
    ("pipx-rns", "pip_rns.cli_pipx", "main"),
)


def _running_from_zip() -> Path | None:
    """Return the .pyz path when modules are loaded from a zipapp."""
    import opip

    file = getattr(opip, "__file__", None) or ""
    if ".pyz" in file.replace("\\", "/"):
        # e.g. /path/opip.pyz/opip/__init__.py
        parts = Path(file).parts
        for i, part in enumerate(parts):
            if part.endswith(".pyz"):
                return Path(*parts[: i + 1])
    return None


def _package_dirs_on_disk() -> dict[str, Path]:
    import opip
    import pip_rns

    opip_file = getattr(opip, "__file__", None)
    pip_file = getattr(pip_rns, "__file__", None)
    if not opip_file or not pip_file:
        raise InstallError("Cannot locate opip/pip_rns package files")
    return {
        "opip": Path(opip_file).resolve().parent,
        "pip_rns": Path(pip_file).resolve().parent,
    }


def _default_bin_dir(user: bool, target: str | None, venv: str | None) -> Path:
    if venv:
        if os.name == "nt":
            return Path(venv) / "Scripts"
        return Path(venv) / "bin"
    if target:
        return Path(target) / ("Scripts" if os.name == "nt" else "bin")
    if user:
        if os.name == "nt":
            base = Path(os.environ.get("APPDATA", Path.home()))
            return base / "Python" / "Scripts"
        return Path.home() / ".local" / "bin"
    return Path(sys.prefix) / ("Scripts" if os.name == "nt" else "bin")


def _default_site_dir(user: bool, target: str | None, venv: str | None) -> Path:
    if target:
        return Path(target)
    if venv:
        pyver = f"python{sys.version_info.major}.{sys.version_info.minor}"
        if os.name == "nt":
            return Path(venv) / "Lib" / "site-packages"
        return Path(venv) / "lib" / pyver / "site-packages"
    if user:
        path = site.getusersitepackages()
        if isinstance(path, list):
            path = path[0]
        return Path(path)
    return Path(site.getsitepackages()[0])


def _write_shim(bin_dir: Path, name: str, module: str, attr: str, python: str) -> Path:
    bin_dir.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        path = bin_dir / f"{name}.exe"
        # Write a .cmd launcher instead of a binary
        path = bin_dir / f"{name}.cmd"
        content = (
            "@echo off\r\n"
            f'"{python}" -c "from {module} import {attr}; '
            f'import sys; sys.exit({attr}())" %*\r\n'
        )
        path.write_text(content, encoding="utf-8")
        return path

    path = bin_dir / name
    content = (
        f"#!{python}\n"
        f"# generated by opip/pip-rns self-install\n"
        f"import sys\n"
        f"from {module} import {attr}\n"
        f"if __name__ == '__main__':\n"
        f"    sys.exit({attr}())\n"
    )
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)
    return path


def _copy_packages_from_disk(site_dir: Path) -> None:
    packages = _package_dirs_on_disk()
    site_dir.mkdir(parents=True, exist_ok=True)
    for name, src in packages.items():
        dest = site_dir / name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(
            src,
            dest,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
        )


def _copy_packages_from_zip(pyz: Path, site_dir: Path) -> None:
    site_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(pyz, "r") as zf:
        for name in ("opip", "pip_rns"):
            dest = site_dir / name
            if dest.exists():
                shutil.rmtree(dest)
            dest.mkdir(parents=True)
            prefix = name + "/"
            for info in zf.infolist():
                if not info.filename.startswith(prefix):
                    continue
                if info.is_dir():
                    continue
                rel = info.filename[len(prefix) :]
                if not rel or "__pycache__" in rel or rel.endswith((".pyc", ".pyo")):
                    continue
                out = dest / rel
                out.parent.mkdir(parents=True, exist_ok=True)
                with zf.open(info, "r") as src, open(out, "wb") as dst:
                    shutil.copyfileobj(src, dst)


def _find_sibling_wheel() -> Path | None:
    """Look for pip_rns-*.whl next to the running zipapp or cwd/dist."""
    candidates: list[Path] = []
    pyz = _running_from_zip()
    if pyz:
        candidates.append(pyz.parent)
    candidates.append(Path.cwd())
    candidates.append(Path.cwd() / "dist")
    for base in candidates:
        if not base.is_dir():
            continue
        wheels = sorted(base.glob("pip_rns-*.whl")) + sorted(base.glob("pip-rns-*.whl"))
        if wheels:
            return wheels[-1]
    return None


def self_install(
    *,
    user: bool = False,
    target: str | None = None,
    venv: str | None = None,
    prefer_uv: bool = True,
    no_interactive: bool = True,
) -> dict:
    """Install opip and pip-rns for the current user/venv/target without system pip.

    Preference order:
    1. sibling wheel via uv (if available)
    2. sibling wheel via ensurepip-in-venv then pip
    3. manual copy of packages from zipapp or source tree + shims
    """
    from opip import terminal

    if sum(bool(x) for x in (user, target, venv)) > 1:
        raise InstallError("Use only one of --user, --target, or --venv")

    if not user and not target and not venv:
        user = True

    python = sys.executable
    if venv:
        venv = ensure_venv(venv, no_interactive=no_interactive)
        python = (
            str(Path(venv) / "Scripts" / "python.exe")
            if os.name == "nt"
            else str(Path(venv) / "bin" / "python")
        )

    site_dir = _default_site_dir(user=user, target=target, venv=venv)
    bin_dir = _default_bin_dir(user=user, target=target, venv=venv)
    wheel = _find_sibling_wheel()
    method = "manual"

    if wheel and prefer_uv and _uv_available():
        terminal.info(f"Installing {wheel.name} with uv")
        cmd = [
            "uv",
            "pip",
            "install",
            "--python",
            python,
            "--no-deps",
            str(wheel),
        ]
        if target:
            cmd.extend(["--target", str(site_dir)])
        elif user and not venv:
            cmd.append("--user")
            cmd.append("--break-system-packages")
        import subprocess

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise InstallError(f"uv install failed:\n{result.stderr or result.stdout}")
        method = "uv"
    elif wheel and venv and _find_pip(python):
        terminal.info(f"Installing {wheel.name} with pip in venv")
        import subprocess

        result = subprocess.run(
            [python, "-m", "pip", "install", "--no-deps", str(wheel)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise InstallError(f"pip install failed:\n{result.stderr or result.stdout}")
        method = "pip"
    elif wheel and not venv:
        terminal.info(f"Extracting {wheel.name} into {site_dir}")
        install_wheel_manual(str(wheel), str(site_dir))
        method = "manual-wheel"
    else:
        pyz = _running_from_zip()
        terminal.info(f"Copying packages into {site_dir}")
        if pyz and pyz.is_file():
            _copy_packages_from_zip(pyz, site_dir)
        else:
            _copy_packages_from_disk(site_dir)
        method = "manual-copy"

    written = []
    for name, module, attr in SHIMS:
        written.append(str(_write_shim(bin_dir, name, module, attr, python)))

    terminal.success(f"self-install complete ({method})")
    terminal.info(f"Packages: {site_dir}")
    terminal.info(f"Scripts:  {bin_dir}")
    if str(bin_dir) not in os.environ.get("PATH", "").split(os.pathsep):
        terminal.warn(f"Add to PATH: {bin_dir}")

    return {
        "method": method,
        "site_dir": str(site_dir),
        "bin_dir": str(bin_dir),
        "scripts": written,
        "python": python,
    }
